build:
	./configure --prefix=$(PKG_DIR) --with-arch=rv32imac --with-cmodel=medlow --enable-multilib
	make all install
	cp riscv.ld $(PKG_DIR)/riscv32-unknown-elf/lib

checkout:
	git submodule update --init